name: On Merge to master
on:
    pull_request:
     branches:
      - master
     types:
     - closed 

jobs:
    on-merge:
        runs-on: ubuntu-latest
        steps:
        - name: Check if master branch is updated
          if: github.event.name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github_event.pull_request.base.ref == 'master'
          run: |
            echo "Workflowtriggered after merging with main"
