name: On Merge to main
on:
    pull_request:
     branches:
      - main
     types:
     - closed 

jobs:
    on-merge:
        runs-on: ubuntu-latest
        steps:
        - name: Check if main branch is updated
          if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
          run: |
            echo "Workflowtriggered after merging with main"
